services:
  db:
    image: postgres:17.5
    container_name: fortnite-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fortnite
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - fortnite-data:/var/lib/postgresql/data
    networks:
      - fortnite-network

  backend:
    build: .
    container_name: fortnite-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_URL: jdbc:postgresql://db:5432/fortnite
      DB_USERNAME: admin
      DB_PASSWORD: admin
      JWT_SECRET: f2c4e630370728019a8eb799a24ab406
      APP_URL: http://localhost:8080
    depends_on:
      - db
    networks:
      - fortnite-network
    restart: unless-stopped

  adminer:
    image: adminer:5.3.0
    container_name: fortnite-adminer
    ports:
      - "8081:8080"
    networks:
      - fortnite-network
    depends_on:
      - db

networks:
  fortnite-network:

volumes:
  fortnite-data: