spring:
  application:
    name: backendFortnite
  app:
    url: ${APP_URL:http://localhost:8080/}
  datasource:
    url: ${DB_URL:jdbc:postgresql://db:5432/fortnite}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
  messages:
    encoding: UTF-8
jwt:
  secret: ${JWT_SECRET:f2c4e630370728019a8eb799a24ab406}
server:
  error:
    include-stacktrace: always
  port: 8080