spring:
  application:
    name: backendFortnite
  app:
    url: ${APP_URL:https://seu-backend.onrender.com}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      jdbc:
          batch_size: 20
      order_inserts: true
      order_updates: true
    properties:
      hibernate.format_sql: false
  messages:
    encoding: UTF-8
  task:
    scheduling:
      enabled: true
jwt:
  secret: ${JWT_SECRET}

server:
  error:
    include-stacktrace: never
  port: ${PORT:8080}
  servlet:
    context-path: /
app:
  scheduler:
    initial-delay: 30000
    enabled: true